### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by vavsab** [s0/git-publish-subdir-action#104]
Hi team. Could you please make a release? 
I do not feel comfortable using `@master` but the last release is too old :(

**Comment by s0** [comment]
Hey, probably best to actually pin the specific commit of the version you want to use, ala: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

I currently don't have time to maintain this repo in my free time unfortunately

**Comment by vavsab** [comment]
Got you. Will stay with master then
