### ISSUE TITLE
Personalized commit message?

### ISSUE THREAD

**Issue by equiman** [s0/git-publish-subdir-action#12]
First, I want to thank you because of this **action** it's awesome.

I'm publishing automatically a console application made in .net core to Windows and macOS:
https://github.com/deinsoftware/hardhat/blob/master/.github/workflows/release.yml

The only thing, it's that I used the commit message to show to my users what was updated. There is a way to define a personalized message on commit?

**Comment by oliverclark15** [comment]
Came here to also ask this.

**Comment by s0** [comment]
Sorry for the delay, it's been a crazy couple of months, i think this is a great idea!

I think allowing for users to define a custom commit message template with some placeholders (including the commit message of the current HEAD) would be very valuable.

I plan on working on this today / tomorrow. I'll let you know how I get on!

**Comment by oliverclark15** [comment]
Yes! Even an option to use the same commit message that triggered the action would be awesome. Thanks for your awesome action it has been so useful.

**Comment by s0** [comment]
All done: https://github.com/s0/git-publish-subdir-action/releases/tag/v2.3.0 :)

set `MESSAGE: "{msg}"` to get the desired result!

**Comment by equiman** [comment]
Amazing. Thanks!
