### ISSUE TITLE
FR: Only create commit if index has changed

### ISSUE THREAD

**Issue by kruton** [s0/git-publish-subdir-action#21]
I'd like to only create a commit and push to the branch if any new files were created or changed (i.e., the index has changed).

**Comment by s0** [comment]
This is a good idea. I think I'd like to introduce it as an option though, as it's sometimes nice to see the additional commits.

**Comment by s0** [comment]
This feature has now been added with the environment variable `SKIP_EMPTY_COMMITS=true`, and is part of the [v2.4.0](https://github.com/s0/git-publish-subdir-action/releases/tag/v2.4.0) release.
