### ISSUE TITLE
Allow customization of folder clean operation

### ISSUE THREAD

**Issue by ionutradu-tm** [s0/git-publish-subdir-action#24]
Is it possible to update the existing branch? Currently it removes everything.

desired functionality:

the current content is

directory1/file1
directoru1/file2
directory2

the content directory to upload is:
directory1/file1 

result:
keep directory1/file2 and directory2 and update directory1/file1

**Comment by s0** [comment]
Hmm that's an interesting use case. I think we need to be more explicit about how it handles existing directories / sub directories. would it recursively keep everything, and only copy over the files that have changed, or would there sometimes be sub directories that need to be cleaned, but not the root directory itself? Perhaps it would be most useful to provide a way for the user to run their own script to "clean" the directory (rather than cleaning everything), and then just copying over what's already there? That script could of course do nothing, which would then behave like the way you describe?

**Comment by ionutradu-tm** [comment]
Hey,
Thank you very much for your prompt answer. Yes, a cleanup script is a better idea (it will avoid another future requests :-) )., but even here I would like to have the option tu run it on a new branch or an existing branch.
so
1) new branch: just copy the files/directories/sub directories  on a en empty root directory (git init), currently implemented.
2) existing branch: run cleanup script (if existis), and then copy/override the files/directories/sub directories

**Comment by JesFot** [comment]
May I propose the use of a file that lists ignored files (just like ``.gitignore``). Listed files in this one would not be removed.

**Comment by dylanrussellmd** [comment]
Just saying that I found this open issue because I am requesting the exact same use case. Thanks!

**Comment by JesFot** [comment]
In addition of my proposal, I'll drop here a command to delete all files except those in the ``.gitignore`` and the ``.gitignore`` itself.
```shell
git rm -rf -- $(git ls-files --exclude-from=.gitignore -cmok | grep -v .gitignore)
```
``git rm`` is already ignoring files from the ``.gitignore`` BUT it does remove the ``.gitignore`` file itself, and does not allow for a different file than the ``.gitignore``

**Comment by JesFot** [comment]
In addition to my proposal, I'll suggest the ``grep`` command:
```shell
git rm -rf -- $(git ls-files -cmok | grep -v -f .docignore)
```
In this case grep will prevent files that matches a REGEX pattern inside the ``.docignore`` file to be listed and therefore deleted.
The ``.docignore`` might be provided by a configuration element.

Also, I have not tested this line so I cannot assure that it is working perfectly.

**Comment by s0** [comment]
If we're going to glob / ignore file route, we definitely want to see if we can take advantage of an existing library that handles those files, or something like https://github.com/isaacs/node-glob

**Comment by s0** [comment]
This has now been included in the latest release: https://github.com/s0/git-publish-subdir-action/releases/tag/v2.5.0
