### ISSUE TITLE
First commit message

### ISSUE THREAD

**Issue by ionutradu-tm** [s0/git-publish-subdir-action#25]
Hey,

Is it possible to:
1) prefix first commit message with [ci skip]
2) better way: custom message (env variable)

Thank you!

**Comment by s0** [comment]
Ah, you mean the message that says `@Initial <branch> commit`? Yeah that's currently hard-coded, but there's no reason why I shouldn't be able to make that configurable. I'll look into that now.

**Comment by s0** [comment]
Hmm actually on second thought, the initial commit before the "main" commit is unnecessary, and it would be better to just remove it altogether. You can already customize the commit message of other commits. I'll work on removing that commit now.

**Comment by s0** [comment]
This has now been done and is part of the [v2.4.0](https://github.com/s0/git-publish-subdir-action/releases/tag/v2.4.0) release.

**Comment by ionutradu-tm** [comment]
yes, is better to remove it.

thank you !
