### ISSUE TITLE
[bug?] `CLEAR_GLOBS_FILE` doesn't seem to work

### ISSUE THREAD

**Issue by keunes** [s0/git-publish-subdir-action#57]
Hello!

Thank you for this GitHub action! I'm using it for the website of the FOSS podcast app AntennaPod.

I didn't understand why the whole target branch was wiped, until I read the README about [Custom clear operations](https://github.com/s0/git-publish-subdir-action#custom-clear-operations).

I created the file `.github/workflows/.clear-target-files` with the following contents:
```
!translations/contribute-pages/*
!translations/documentation-pages/*
!translations/general-pages/*
!translations/general-strings/*
```

However, none of the files I manually created in the target branch are actually deleted. I would expect the following items in the target items to be deleted:
```
translations/contribute/site-contribute_nl.po
translations/testing.md
```

The behaviour of the action is as if the `CLEAR_GLOBS_FILE` is empty, in which case target branch is not cleared at all. Could this be a bug?

**Comment by keunes** [comment]
I saw [this code in the PR introducing the feature](https://github.com/s0/git-publish-subdir-action/pull/43/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.snap&file-filters%5B%5D=.ts#diff-2edab5e59322f59d31873ad7bf9f172e9f4f62bf001c4cdb4a54273130c124c4R544). So I added
```
**/*
!.git
```
to my `.clear-target-files` file, and now it works as expected :)

I'm wondering if there should be a setting allowing to choose between 'wipe all except what is in `CLEAR_GLOBS_FILE`' and 'wipe only items listed in `CLEAR_GLOBS_FILE`'.

**Comment by s0** [comment]
Perhaps the README is not clear enough that using `CLEAR_GLOBS_FILE` replaces the default behavior of clearing everything, I'll clarify the documentation to make it clear that's the case, but I don't think adding another option will be the right solution, as it will complicate the code unnecessarily, given it's already configurable adding the lines you've written (which i'll also add to the README)
