### ISSUE TITLE
Dot started files are not uploaded.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [s0/git-publish-subdir-action#6]
I have file named ".MyRootFile". Its name starts with dot.
This file is on workflow root folder but do not upload to remote repository.

**Comment by nolanbconaway** [comment]
Same problem! This was not an issue a month or two ago, did something change?

**Comment by benfavre** [comment]
I'm experiencing this also

**Comment by s0** [comment]
Hey, sorry for the delay, I'm taking a look at this now!



> I'm experiencing this also, but if you fix it, and you have workflow files you end up with an error
> (refusing to allow a bot to create or update workflow `.github/workflows/), so I guess it's a safeguard

It's not an intentional safeguard at least, there are many legitimate circumstances for adding dotfiles that don't include workflow files =)

**Comment by s0** [comment]
Fixed and published a new version: https://github.com/s0/git-publish-subdir-action/releases/tag/v2.1.0
