### ISSUE TITLE
Allow for non-root target directory

### ISSUE THREAD

**Issue by s0** [s0/git-publish-subdir-action#70]
There have been a number of requests around pushing to sub-directories of target branches, rather than the root. This is possible with a custom `CLEAR_GLOBS_FILE` file, and by replicating the structure of the target directory, but this usage could be significantly simplified.

(e.g. #64, #65, etc...)

**Comment by jdcmarques** [comment]
Hey, just opened a PR with an implementation for this, can you take a look?

#82
